### ISSUE TITLE
Particle runtime panic

### ISSUE THREAD

**Issue by nzlov** [KorokEngine/alpha-demo#1]
# Output
```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
korok.io/korok/gfx.(*SpriteRenderFeature).Draw(0xc4200aa600, 0xc4200b2060, 0x1, 0x1)
	/Users/qipeng/workspace/go/src/korok.io/korok/gfx/sprite.go:254 +0x29c
korok.io/korok/gfx.(*RenderSystem).Update(0xc4200ca210, 0x7fff3c1a1996)
	/Users/qipeng/workspace/go/src/korok.io/korok/gfx/render_system.go:132 +0x29e
korok.io/korok/game.(*Game).Update(0xc4201b2000)
	/Users/qipeng/workspace/go/src/korok.io/korok/game/game.go:244 +0x110
korok.io/korok/game.(*Game).OnLoop(0xc4201b2000)
	/Users/qipeng/workspace/go/src/korok.io/korok/game/game.go:71 +0x2b
korok.io/korok/hid.CreateWindow(0xc420065ee0)
	/Users/qipeng/workspace/go/src/korok.io/korok/hid/window_glfw.go:134 +0x48b
korok.io/korok.Run(0xc420065f40, 0x41e54e0, 0x42ca508)
	/Users/qipeng/workspace/go/src/korok.io/korok/korok.go:69 +0x87b
main.main()
	/Users/qipeng/workspace/go/src/beta-demo/particle/main.go:54 +0x97
exit status 2
```

**Comment by ntop001** [comment]
这个问题一直无法复现，暂时关闭吧
